package com.xworkz.datatypes.examples;

public class Clock {
    
	public String color;
    public String material;
    public String frameMaterial;
    public String brandName;
    public String shape;
    public String model;
    public int weight;
    public int numberOfHands; 
    public int price;
    public boolean numberIsInteger ;
    public boolean isNumberFormat;
    public String type;
    public int size;
    public int hours;
    public int minutes;
    public int seconds;
    public boolean isPopularInIndia;
    public boolean isDigital;
    public String warranty;
    public boolean hasAlarm;
    public boolean is24HourFormat;
    public String handsColour;
    public String numberColor;
    public boolean hasManufacturedate;
    public boolean isPopularBrand;
    public boolean isOldestModel;
    public boolean usedAnywhere;
    public boolean hasSnoozeButton;
    public boolean isAtomicClock;
    public boolean hasTemperatureDisplay;
    public boolean isRadioControlled;
    public boolean hasNightLight;
    public boolean hasChime;
    public boolean isBluetoothEnabled;
    public boolean isSmartClock;
    public boolean hasBattery;
    public boolean isElectricPowered;
    public boolean isSolarPowered;
    public boolean hasDaylightSavingTime;
    public boolean hasMultipleTimezones;
    public boolean hasDateDisplay;
    public boolean isWaterproof;
    public boolean isShockproof;
    public boolean isAntique;
    public boolean isModern;
    public boolean isAnalog;
    public boolean isHourlyChime;
    public boolean hasDigitalDisplay;
    public boolean hasCountdownTimer;
    public boolean hasStopwatch;
    public boolean hasCalendar;
    public boolean hasBacklight;
    public boolean hasBluetoothSpeaker;
    public boolean hasVoiceControl;
    public boolean isDecorative;
    public boolean hasRemoteControl;
    public boolean hasUSBPort;
    public boolean hasCustomizableFace;
    public boolean hasNFC;
    public boolean isWiFiConnected;
    public boolean hasLoudAlarm;
    public boolean hasSleepTimer;
    public boolean hasInclinometer;
    public boolean hasBarometer;
    public boolean hasHikingFeatures;
    public boolean hasMoonPhaseDisplay;
    public boolean hasDigitalRadio;
    public boolean hasBluetoothHeadset;
    public boolean hasWeightedBase;
    public boolean isDesktopClock;
    public boolean isWallClock;
    public boolean isCuckooClock;
    public boolean isPendulumClock;
    public String manufacturedCoutry;
    public int established ;
    public boolean hasWoodenFrame;
    public boolean hasMetallicFinish;
    public String founder ;
    public boolean hasModernDesign;
    public boolean hasAlarmVolumeControl;
    public boolean hasAutoTimeSync;
    
    
    public void displayClockDetails()
    {
    	System.out.println("clock color:"+color);
    	System.out.println("clock material:"+material);
    	System.out.println("clock framemerial:"+frameMaterial);
    	System.out.println("clock brandname :"+brandName);
    	System.out.println("clock shape:"+shape);
    	System.out.println("clock model:"+model);
    	System.out.println("clock weight:"+weight);
    	System.out.println("noofhands:"+numberOfHands);
    	System.out.println("clock price :"+ price);
    	System.out.println("clock number is integer :"+numberIsInteger);
    	System.out.println("clock is number format:"+isNumberFormat);
    	System.out.println("clock type:"+type);
    	System.out.println("clock size:"+size);
    	System.out.println("clock hours:"+hours);
    	System.out.println("clock minutes:"+minutes);
    	System.out.println("clock seconds:"+seconds);
    	System.out.println("clock is popular india:"+isPopularInIndia);
    	System.out.println("clock isDigital:" + isDigital);
    	System.out.println("clock warranty:"+warranty);
    	System.out.println("clock hasAlarm :"+hasAlarm);
    	System.out.println("clock is24HourFormat:"+is24HourFormat);
    	System.out.println("clock handsColour:"+handsColour);
    	System.out.println("clock numberColor:"+ numberColor);
    	System.out.println("clock hasManufacturedate:"+ hasManufacturedate);
    	System.out.println("clock isPopularBrand :"+ isPopularBrand);
    	System.out.println("clock isOldestModel:"+isOldestModel);
    	System.out.println("clock usedAnywhere:"+usedAnywhere);
    	System.out.println("clock hasSnoozeButton:"+hasSnoozeButton);
    	System.out.println("clock isAtomicClock:"+isAtomicClock);
    	System.out.println("clock hasTemperatureDisplay:"+hasTemperatureDisplay);
    	System.out.println("clock isRadioControlled :"+ isRadioControlled);
    	System.out.println("clock hasNightLight:"+hasNightLight);
    	System.out.println("clock hasChime:"+hasChime);
    	System.out.println("clock isBluetoothEnabled:"+isBluetoothEnabled);
    	System.out.println("clock isSmartClock:"+isSmartClock);
    	System.out.println("clock hasBattery:"+hasBattery);
    	System.out.println("clock isElectricPowered:"+isElectricPowered);
    	System.out.println("clock isSolarPowered:"+isSolarPowered);
    	System.out.println("clock hasDaylightSavingTime:"+hasDaylightSavingTime);
    	System.out.println("clock hasMultipleTimezones:"+ hasMultipleTimezones);
    	System.out.println("clock hasDateDisplay:"+hasDateDisplay);
    	System.out.println("clock isWaterproof:"+isWaterproof);
    	System.out.println("clock isShockproof:"+isShockproof);
    	System.out.println("clock isAntique:"+isAntique);
    	System.out.println("clock isModern:"+isModern);
    	System.out.println("clock  isAnalog:"+ isAnalog);
    	System.out.println("clock isHourlyChime:"+isHourlyChime);
    	System.out.println("clock hasDigitalDisplay:"+hasDigitalDisplay);
    	System.out.println("clock  hasCountdownTimer:"+ hasCountdownTimer);
    	System.out.println("clock hasStopwatch:"+hasStopwatch);
    	System.out.println("clock hasCalendar:"+hasCalendar);
    	System.out.println("clock hasBacklight:"+hasBacklight);
    	System.out.println("clock hasBluetoothSpeaker:"+hasBluetoothSpeaker);
    	System.out.println("clock hasVoiceControl:"+hasVoiceControl);
    	System.out.println("clock isDecorative:"+isDecorative);
    	System.out.println("clock hasRemoteControl:"+hasRemoteControl);
    	System.out.println("clock hasUSBPort:"+hasUSBPort);
    	System.out.println("clock hasCustomizableFace:"+hasCustomizableFace);
    	System.out.println("clock hasNFC:"+hasNFC);
    	System.out.println("clock isWiFiConnected:"+isWiFiConnected);
    	System.out.println("clock hasLoudAlarm:"+hasLoudAlarm);
    	System.out.println("clock  hasSleepTimer:"+ hasSleepTimer);
    	System.out.println("clock hasInclinometer:"+hasInclinometer);
    	System.out.println("clock hasBarometer:"+hasBarometer);
    	System.out.println("clock hasHikingFeatures:"+hasHikingFeatures);
    	System.out.println("clock hasMoonPhaseDisplay:"+hasMoonPhaseDisplay);
    	System.out.println("clock  hasDigitalRadio:"+ hasDigitalRadio);
    	System.out.println("clock hasBluetoothHeadset:"+hasBluetoothHeadset);
    	System.out.println("clock hasWeightedBase:"+hasWeightedBase);
    	System.out.println("clock isDesktopClock:"+isDesktopClock);
    	System.out.println("clock isWallClock:"+isWallClock);
    	System.out.println("clock isCuckooClock:"+isCuckooClock);
    	System.out.println("clock isPendulumClock:"+isPendulumClock);
    	System.out.println("clock manufacturedCoutry:"+manufacturedCoutry);
    	System.out.println("clock established:"+established);
    	System.out.println("clock hasWoodenFrame:"+hasWoodenFrame);
    	System.out.println("clock  hasMetallicFinish:"+ hasMetallicFinish);
    	System.out.println("clock founder:"+founder);
    	System.out.println("clock hasModernDesign:"+hasModernDesign);
    	System.out.println("clock hasAlarmVolumeControl:"+hasAlarmVolumeControl);
    	System.out.println("clock hasAutoTimeSync:"+hasAutoTimeSync);
    }
    
    	
    	public Clock()
    	{
    		System.out.println("running clock properties");
    	}
}
