package com.xworkz.datatypes.examples;

public class Knife {
	
    public String name;
	public String type;
	public String bladeMaterial;
	public String handleMaterial;
	public int bladeLength;
	public int overallLength;
	public String bladeShape;
	public String grindType;
	public String edgeType;
	public String tangType;
	public String HandleDesign;
	public String weight;
	public String balance;
	public String spineThickness;
	public String deploymentMechanism;
	public String lockingMechanism;
	public String pocketClip;
	public String sheathMaterial;
	public String retentionSystem;
	public String openingMethod;
	public String bladeCoating;
	public String rustResistance;
	public String corrosionResistance;
	public String handleColor;
	public boolean lanyardHole;
	public String scales;
	public String jimping;
	public String pommelType;
	public String bladeThickness;
	public String spineDesign;
	public int bladeSteelHardness;
	public String ambidextrousFeatures;
	public boolean fingerGrooves;
	public String handleLength;
	public String bladeFinish;
	public String ricasso;
	public String bladeSerrationType;
	public String tacticalFeatures;
	public String rearLocking;
	public String gripTexture;
	public boolean fullersGrooves;
	public String fingerGuard;
	public String bladeProfile;
	public String bladeWidth;
	public String handleErgonomics;
	public String mosaicPins;
	public String bladeGeometry;
    public String razorSharpness;
	public String rustproofingTreatment;
	public String bladeBelly;
	public int bladeAngle;
	public String customizationOptions;
	public int bladeSteelComposition;
	public String thumbRamp;
	public String easeofSharpening;
	public String legalBladeLength;
	public String tensionAdjustment;
	public String lockbarStabilizer;
	public String assistedOpeningSpeed;
	public String bladeBackThickness;
	public String purpose;
	public String backspacerDesign;											
	public String handleInlays;												
	public String gentlemanFolderFeatures;											
	public String detentStrength;														
	public String bladeHoles;															
	public String lockbarAccess;														
	public String handleThickness;														
	public String nonReflectiveFinish;													
	public String thumbDisc;																
	public String handleContours;													
	public String trailingPoint;														
	public String bladeMaterialOrigin;											
	public String heatTreatmentMethod;											
	public String ceramicBladeOption;											
	public String rustEradicationFeatures;												
	public String handleShape;															
	public String specializedCoating;
	public int warranty;
	public String pivotType;
	
	public void displayKniefDetails()
	{
	    System.out.println("knife name:"+name);
		System.out.println("knife type:"+type);
		System.out.println("knife bladeMaterial:"+ bladeMaterial);
		System.out.println("knife handleMaterial:"+handleMaterial);
		System.out.println("knife bladeLength:"+ bladeLength);
		System.out.println("knife overallLength:"+overallLength);
		System.out.println("knife bladeShape:"+bladeShape);
		System.out.println("knife grindType:"+grindType);
		System.out.println("knife edgeType:"+edgeType);
		System.out.println("knife tangType:"+tangType);
		System.out.println("knife HandleDesign:"+HandleDesign);
		System.out.println("knife weight:"+weight);
		System.out.println("knife balance:"+balance);
		System.out.println("knife spineThickness:"+spineThickness);
		System.out.println("knife deploymentMechanism:"+deploymentMechanism);
		System.out.println("knife lockingMechanism:"+lockingMechanism);
		System.out.println("knife pocketClip:"+pocketClip);
		System.out.println("knife sheathMaterial:"+sheathMaterial);
		System.out.println("knife retentionSystem:"+retentionSystem);
		System.out.println("knife openingMethod:"+openingMethod);
		System.out.println("knife bladeCoating:"+bladeCoating);
		System.out.println("knife rustResistance:"+rustResistance);
		System.out.println("knife corrosionResistance:"+corrosionResistance);
		System.out.println("knife handleColor:"+handleColor);
		System.out.println("knife lanyardHole:"+lanyardHole);
		System.out.println("knife scales:"+scales);
		System.out.println("knife jimping:"+jimping);
		System.out.println("knife pommelType:"+pommelType);
		System.out.println("knife bladeThickness:"+bladeThickness);
		System.out.println("knife spineDesign:"+spineDesign);
		System.out.println("knife bladeSteelHardness:"+bladeSteelHardness);
		System.out.println("knife ambidextrousFeatures:"+ambidextrousFeatures);
		System.out.println("knife fingerGrooves:"+ fingerGrooves);
		System.out.println("knife handleLength:"+handleLength);
		System.out.println("knife bladeFinish:"+bladeFinish);
		System.out.println("knife ricasso:"+ricasso);
		System.out.println("knife bladeSerrationType:"+bladeSerrationType);
		System.out.println("knife tacticalFeatures:"+tacticalFeatures);
		System.out.println("knife rearLocking:"+rearLocking);
		System.out.println("knife gripTexture:"+gripTexture);
		System.out.println("knife fullersGrooves:"+fullersGrooves);
		System.out.println("knife fingerGuard:"+fingerGuard);
		System.out.println("knife bladeProfile:"+bladeProfile);
		System.out.println("knife bladeWidth:"+bladeWidth);
		System.out.println("knife handleErgonomics:"+ handleErgonomics);
		System.out.println("knife mosaicPins:"+ mosaicPins);
		System.out.println("knife bladeGeometry:"+bladeGeometry);
		System.out.println("knife razorSharpness:"+razorSharpness);
		System.out.println("knife rustproofingTreatment:"+rustproofingTreatment);
		System.out.println("knife bladeBelly:"+bladeBelly);
		System.out.println("knife bladeAngle:"+bladeAngle);
		System.out.println("knife customizationOptions:"+customizationOptions);
		System.out.println("knife bladeSteelComposition:"+ bladeSteelComposition);
		System.out.println("knife thumbRamp:"+thumbRamp);
		System.out.println("knife easeofSharpening:"+easeofSharpening);
		System.out.println("knife legalBladeLength:"+legalBladeLength);
		System.out.println("knife tensionAdjustment:"+tensionAdjustment);
		System.out.println("knife.lockbarStabilizer:"+lockbarStabilizer);
		System.out.println("knife assistedOpeningSpeed:"+assistedOpeningSpeed);
		System.out.println("knife bladeBackThickness:"+bladeBackThickness);
		System.out.println("knife purpose:"+purpose);
		System.out.println("knife backspacerDesign:"+backspacerDesign);
		System.out.println("knife handleInlays:"+handleInlays);
		System.out.println("knife gentlemanFolderFeatures:"+gentlemanFolderFeatures);
		System.out.println("knife detentStrength:"+detentStrength);
		System.out.println("knife bladeHoles:"+bladeHoles);
		System.out.println("knife lockbarAccess:"+ lockbarAccess);
		System.out.println("knife handleThickness:"+handleThickness);
		System.out.println("knife nonReflectiveFinish:"+nonReflectiveFinish);
		System.out.println("knife thumbDisc:"+thumbDisc);
		System.out.println("knife handleContours:"+ handleContours);
		System.out.println("knife trailingPoint:"+trailingPoint);
		System.out.println("knife bladeMaterialOrigin:"+bladeMaterialOrigin);
		System.out.println("knife heatTreatmentMethod:"+heatTreatmentMethod);
		System.out.println("knife ceramicBladeOption:"+ceramicBladeOption);
		System.out.println("knife rustEradicationFeatures:"+rustEradicationFeatures);
		System.out.println("knife handleShape:"+handleShape);
		System.out.println("knife specializedCoating:"+specializedCoating);
		System.out.println("knife warranty:"+warranty);
		System.out.println("knife pivotType:"+pivotType);	
	}
	
	public Knife()
	{
		System.out.println("Running Knief properties");
	}

}
