package com.xworkz.datatypes.examples;

public class Paste {
	
    public String brandName;
    public String productName; 
    public String flavor;
    public String size;
    public int price;    
    public String born;
    public int bornYear;
    public String died;
    public int diedYear;  
    public String boxshape;
    public boolean ingredients;
    public boolean hasDescription;
    public boolean isWhitening;  
    public int NoOfChildren;
    public String noOfChildrenchildrensName; 
    public String FatherName;
    public String motherName;
    public String Spouse;   
    public String whoIstheIndianCEOOfColgate;    
    public String whoOwnsColgate;
    public String whichCountryOwnsColgate;
    public boolean isChildrenFriendly;
    public String expirationDate;
    public long barcode;
    public String manufactureDate;
    public String madeIn;    
    public String founder;
    public String ManufacturedBy;
    public int foundedYear;
    public String pasteColour;
    public String boxColour;
    public String  capColour;    
    public String capShape;
	public int pHLevel;
	public boolean itProvidesDiffernetQuantity;
	public String productFormulation;	
	public boolean isSensitiveRelief;
	public boolean isChildLockCap;
	public String packagingType;
	public String capDesign;	
    public boolean hasHerbalExtracts;
    public boolean hasStainRemovalCapability;
    public boolean hasDiffirentPrice;
    public boolean hasLogo;
	public String Features;	
    public boolean isUsedForGoldJewelleryCleaning;
    public boolean isUsedForSilverChainCleaning;
    public boolean ForWhiteShoeCleaning;
    public boolean itsContainSalt;
    public String brandAmbassadorOfColgate;
    public String colgateHeadQuarters;
    public String areaServed;
    public int noOfEmployee;
    public String howManyYearsHasItBeenFounded;
    public String operatingIncome;
    public String netIncome;
    public String totalAssets;
    public String totalEquity;
    public String revenue;
    public String website;
    public String whenDidColgateStartInIndia; 
    public String colgateOriginalname;
    public String WhichCompanyOwnsColgateInIndia;
    public String whichCityIsColgateOfIndia;
    public String sloganOfColgate;
    public boolean isTheBiggestBrandInTheWorld;
    public String colgateAnnualSales;
    public String whyIsColgateFamous;
    public String whatIsColgateFamousFor;
    public String whichIsMotherBrandOfColgate;
    public String shareOfColgateInIndia;	
    public boolean isPrivate;
    public boolean isPublic;
    public String itsSpell;
    public String useOfDuration;
    public boolean IsFreshnessBreath;
    public String flourideContent;
    public String isApprovedBy;
    public boolean isAvialableIn10rs;
    public boolean itsTasteIsGood;
	
	
	
	public void displayPasteDetails()
	{
	  System.out.println(brandName);
	  System.out.println(productName);
	  System.out.println(flavor);
	  System.out.println(size);
	  System.out.println(price);
	  System.out.println(born);
	  System.out.println(bornYear);
	  System.out.println(died);
	  System.out.println(diedYear);
	  System.out.println(boxshape);		
	  System.out.println(ingredients);
	  System.out.println(hasDescription);	
	  System.out.println(isWhitening);
	  System.out.println(NoOfChildren);
	  System.out.println(noOfChildrenchildrensName);
	  System.out.println(FatherName);
	  System.out.println(motherName);
	  System.out.println(Spouse);
	  System.out.println(whoIstheIndianCEOOfColgate);
	  System.out.println(whoOwnsColgate);
	  System.out.println(whichCountryOwnsColgate);
	  System.out.println(isChildrenFriendly);
	  System.out.println(expirationDate);
	  System.out.println(barcode);
	  System.out.println(manufactureDate);
	  System.out.println(madeIn);
	  System.out.println(founder);
	  System.out.println(ManufacturedBy);
	  System.out.println(foundedYear);
	  System.out.println(pasteColour);
	  System.out.println(boxColour);
	  System.out.println(capColour);
	  System.out.println(capShape);
	  System.out.println(pHLevel);
	  System.out.println(itProvidesDiffernetQuantity);
	  System.out.println(productFormulation);
	  System.out.println(isSensitiveRelief);
	  System.out.println(isChildLockCap);
	  System.out.println(packagingType);
	  System.out.println(capDesign);
	  System.out.println(hasHerbalExtracts);
	  System.out.println(hasStainRemovalCapability);
	  System.out.println(hasDiffirentPrice);
	  System.out.println(hasLogo);	
	  System.out.println(Features);
	  System.out.println(isUsedForGoldJewelleryCleaning);
	  System.out.println(isUsedForSilverChainCleaning);
	  System.out.println(ForWhiteShoeCleaning);
	  System.out.println(itsContainSalt);
	  System.out.println(brandAmbassadorOfColgate);
	  System.out.println(hasStainRemovalCapability);
      System.out.println(colgateHeadQuarters);
	  System.out.println(areaServed);
	  System.out.println(noOfEmployee);
	  System.out.println(howManyYearsHasItBeenFounded); 
	  System.out.println(operatingIncome);
	  System.out.println(netIncome);
	  System.out.println(totalAssets);
	  System.out.println(totalEquity);
	  System.out.println(revenue);
	  System.out.println(website);
	  System.out.println(whenDidColgateStartInIndia); 
	  System.out.println(colgateOriginalname);
	  System.out.println(WhichCompanyOwnsColgateInIndia);
	  System.out.println(whichCityIsColgateOfIndia);
	  System.out.println(sloganOfColgate);
	  System.out.println(isTheBiggestBrandInTheWorld);
	  System.out.println(colgateAnnualSales);
	  System.out.println(whyIsColgateFamous);
	  System.out.println(whatIsColgateFamousFor);
	  System.out.println(shareOfColgateInIndia);
	  System.out.println(isPrivate);
	  System.out.println(isPublic);
	  System.out.println(itsSpell);
	  System.out.println(useOfDuration); 
	  System.out.println(IsFreshnessBreath);
	  System.out.println(flourideContent);
	  System.out.println(isApprovedBy);
	  System.out.println(isAvialableIn10rs);	
	  System.out.println(itsTasteIsGood);
	}
	
	public Paste()
	{
		System.out.println("Running PasteProperties");
	}

}
